services:

  service_link_shortner:
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "./service_link_shortner/healthcheck.sh" ]
      interval: 10s
      timeout: 3s
      retries: 3
    environment:
      APP_TASK: 'api'
      DOCKER_IMAGE_LARAVEL_BASE_VERSION: '${DOCKER_IMAGE_LARAVEL_BASE_VERSION}'
      APP_ENV: '${APP_ENV}'
      APP_NAME: '${LINK_SHORTNER_APP_NAME}'
      APP_URL: '${LINK_SHORTNER_API_URL}'
      APP_KEY: '${LINK_SHORTNER_APP_KEY}'
      APP_DEBUG: '${LINK_SHORTNER_APP_DEBUG}'
      LOG_LEVEL: '${LINK_SHORTNER_LOG_LEVEL}'
      DB_CONNECTION: '${LINK_SHORTNER_DB_CONNECTION}'
      DB_HOST: '${POSTGRES_HOST}'
      DB_PORT: '${POSTGRES_PORT}'
      DB_DATABASE: '${LINK_SHORTNER_DATABASE_NAME}'
      DB_USERNAME: '${POSTGRES_USER}'
      DB_PASSWORD: '${POSTGRES_PASSWORD}'
      REDIS_HOST: '${REDIS_HOST}'
      REDIS_PORT: '${REDIS_PORT}'
      REDIS_USERNAME: '${REDIS_USERNAME}'
      REDIS_PASSWORD: '${REDIS_PASSWORD}'
      REDIS_DB: '${LINK_SHORTNER_REDIS_DB}'
      REDIS_CACHE_DB: '${LINK_SHORTNER_REDIS_CACHE_DB}'
      AWS_ACCESS_KEY_ID: '${LINK_SHORTNER_AWS_ACCESS_KEY_ID}'
      AWS_SECRET_ACCESS_KEY: '${LINK_SHORTNER_AWS_SECRET_ACCESS_KEY}'
      AWS_DEFAULT_REGION: '${LINK_SHORTNER_AWS_DEFAULT_REGION}'
      AWS_BUCKET: '${LINK_SHORTNER_AWS_BUCKET}'
      AWS_ENDPOINT: '${LINK_SHORTNER_AWS_ENDPOINT}'
      AWS_USE_PATH_STYLE_ENDPOINT: '${LINK_SHORTNER_AWS_USE_PATH_STYLE_ENDPOINT}'
      RABBITMQ_HOST: '${RABBITMQ_HOST}'
      RABBITMQ_PORT: '${RABBITMQ_PORT}'
      RABBITMQ_USER: '${RABBITMQ_USERNAME}'
      RABBITMQ_PASSWORD: '${RABBITMQ_PASSWORD}'
      RABBITMQ_VHOST: '${RABBITMQ_VHOST}'
