name: Deploy
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }} 🚀
on:
  push:
      branches:
        - main
jobs:
  Deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /opt
    steps:
      - run: |
          echo "${{ github.workspace }}"
          ls ${{ github.workspace }}
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          path: '/opt'
#      - name: Build Dependencies
#        uses: |
#          sudo chmod +x ./build
#          git pull
